name = "cyclone-web"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"

# Environment variables
[vars]
NODE_VERSION = "18"